### ISSUE TITLE
Wrong relAttribute

### ISSUE THREAD

**Issue by BerndSx** [Leuchtfeuer/typo3-image-gallery#15]
Not sure whether it's an issue or my fault, but I get a wrong relAttribute  for fancybox. 

html shows **rel="fancybox-{field:uid}"** while {field:uid} should be a number.

In partial Image.html
<f:debug>{settings.lightbox.relAttribute}</f:debug>
shows
'fancybox-{field:uid}' (20 chars)

fancybox is not working, only one image shows up.

**Comment by flossels** [comment]
Hi @BerndSx,

which version of this extension do you use? For me it looks like you have to put a "." between the object and the property (i.e. "field.uid" -> this will call the method `$object->getUid()`). Do you have any further information?
