### ISSUE TITLE
Empty file collection description 

### ISSUE THREAD

**Issue by Hammer36** [Leuchtfeuer/typo3-image-gallery#18]
**Describe the bug**
Today I upgraded from from version 4.2.1 to 5.0.0. My TYPO3 instance is on 10.4.14. The file collection attribute 'description' is empty although field 'bm_image_gallery_description' was set in the backend.

**To Reproduce**
Debugging shows that in class Domain/Transfer/CollectionInfo.php method returns an empty string.  The root cause is the wrong use of the null coalescing operator (??).  With an empty string condition it returns an empty string, too. Using a ternary operator (?:) solves the problem.

**Additional context**
The following test code behaves the same in PHP 7 and 8: $x3 gets an empty string because isset()evaluates to true for an empty string.
$x1 = "";
print "x1: '".$x1."'\n";
$x2 = isset($x1);
print "x2: '".$x2."'\n";
$x3 = ($x1) ?? "some text";
print "x3: '".$x3."'\n";
$x4 = ($x1) ? $x1 :  "some text";
print "x4: '".$x4."'\n";

**Comment by flossels** [comment]
This issue duplicates #17 

This should be fixed in the current master.
