### ISSUE TITLE
TER Documentation link invalid

### ISSUE THREAD

**Issue by remonator** [Leuchtfeuer/typo3-image-gallery#19]
On [TER](https://extensions.typo3.org/extension/bm_image_gallery), the [link ](https://docs.typo3.org/p/leuchtfeuer/bm-image-gallery/master/en-us/Introduction/Index.html)to the documentation leads to a 404 Not Found error:

![image](https://user-images.githubusercontent.com/54318829/114005679-1023dc00-9860-11eb-87cc-93dab6174a50.png)

**Comment by flossels** [comment]
Good catch :) Thank you.
I have adjusted the link. Please note that the TER page may still cached.
