### ISSUE TITLE
Exception if description field is empty

### ISSUE THREAD

**Issue by Patta** [Leuchtfeuer/typo3-image-gallery#21]
**Describe the bug**
Exception if the description field of the file collection is empty.

TYPO3 10.4.15
PHP 7.4.16
Composer mode

```
Core: Exception handler (WEB): Uncaught TYPO3 Exception: Argument 1 passed to Leuchtfeuer\BmImageGallery\Domain\Transfer\CollectionInfo::setDescription() must be of the type string, null given, called in /var/www/vhosts/REMOVED/private/typo3conf/ext/bm_image_gallery/Classes/Domain/Transfer/CollectionInfo.php on line 134 | TypeError thrown in file /var/www/vhosts/REMOVED/private/typo3conf/ext/bm_image_gallery/Classes/Domain/Transfer/CollectionInfo.php in line 78. Requested URL: https://REMOVED
```

**Expected behavior**
The description field of a file collection is optional and could be empty.

**Comment by flossels** [comment]
Hi Patta,

have you updated the database? Actually, for the description there should always be an empty string in the DB and not "null".

**Comment by Patta** [comment]
@flossels yes, seems like a upgrade issue. works now. thanks.
