### ISSUE TITLE
ParseError syntax error, unexpected ')' after activating Simple Image Gallery in a 10.4.17 installation

### ISSUE THREAD

**Issue by alexingo** [Leuchtfeuer/typo3-image-gallery#22]
This is the error message: 

in /www/htdocs/.../typo3conf/ext/bm_image_gallery/Configuration/TCA/Overrides/sys_file_collection.php line 53

\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addToAllTCAtypes(
    'sys_file_collection',
    '--div--;LLL:EXT:bm_image_gallery/Resources/Private/Language/locallang_be.xlf:bm_image_gallery_tab,' . implode(',', array_keys($temporaryColumns)),
);

**Comment by bmgrieger** [comment]
Hello @alexingo 

the issue was addressed with the commit [1814cd2](https://github.com/Leuchtfeuer/typo3-image-gallery/commit/1814cd2d406061841efc4ddfd722e3cce5a8ce76) which is contained in the bugfix release **v5.1.1**

The error does not occur with this version anymore.
