### ISSUE TITLE
Add missing null coalescing operator in CollectionInfo.php to prevent exception message

### ISSUE THREAD

**Issue by freshworkx** [Leuchtfeuer/typo3-image-gallery#23]
Prevent exception message:

`Argument 1 passed to Leuchtfeuer\BmImageGallery\Domain\Transfer\CollectionInfo::setDescription() must be of the type string, null given, called in /var/www/html/public/typo3conf/ext/bm_image_gallery/Classes/Domain/Transfer/CollectionInfo.php on line 134`

SQL definition for field "bm_image_gallery_description" is `text`. That means, In TYPO3 context, the default value is `null`.

In CollectionInfo.php:
- the description setter at row 78 defined $description as `string`
- the function call at row 134 only set origin database value
- if description field is empty th default value from DB is `null`
- the exception is thrown

To prevent the exception, add missing null coalescing operator to the function call.

`$this->setDescription($properties['bm_image_gallery_description'] ?? '');`

TYPO3 10.4.17 / bm_image_gallery 5.1.0

**Comment by flossels** [comment]
This seems to be related to #21. Can you check that?

**Comment by freshworkx** [comment]
Looks like the same behavior from #21. It helped me too, to delete the `null` values of  `bm_image_gallery_description` field, to bypass the exception message. But it don´t fixes the fundamental problem. Think about how these values come about.

Imagine the following case:
- have existing `sys_file_collection` records and now install your gallery extension
- new columns are created by TYPO3 => `bm_image_gallery_description text` becomes `ALTER TABLE sys_file_collection ADD bm_image_gallery_description TEXT DEFAULT NULL`
- now you have to deal with `null` values in your database and code

So please implement the `null coalescing operator` as mentioned above OR (as alternative) check and remove these `null` values in your migration wizard

**Comment by flossels** [comment]
Thanks for your detailed description. You're absolutely right and we should implement the coalescing operator. I'll create a PR for this. Thanks :)

**Comment by freshworkx** [comment]
@flossels still no release ?

**Comment by flossels** [comment]
@freshworkx I am no longer part of Leuchtfeuer, so I do not have any permissions to publish a new release. I am sorry...

**Comment by freshworkx** [comment]
@flossels sorry to hear that, i was hoping for a quick release. Who is now responsible for a new release?

**Comment by flossels** [comment]
That's Thomas Esders. I have just spoken to him. Things will be moving here tomorrow 🙃

**Comment by Esders** [comment]
@freshworkx  Hi! Sorry for the delay - for some reason I didn't get a notification about this. We now will work on the release. /CC @flossels
